### ISSUE TITLE
Mobile Support: Increase Content Margins

### ISSUE THREAD

**Issue by alexjohnson505** [seldomskye/neuLadder#2]
On small screens, the body contain should have additional padding (~20px) as to avoid sitting too close to the edges of the device.

**Comment by seldomskye** [comment]
I think this one is actually fixed in this build of the code, I just haven't deployed it yet

Edit: Okay, it's there on everything except the rules page, which makes reading that very difficult

**Comment by seldomskye** [comment]
Fixed in 2a54b8e1aca3d60bd7cf66ee9622c0ca891ddf1f as far as I can tell.

I would almost say bootstrap is over compensating, but not sure
