### ISSUE TITLE
Feature Request: Match History

### ISSUE THREAD

**Issue by alexjohnson505** [seldomskye/neuLadder#3]
Would it be possible to create a list/stream of previous matches? Who beat who, in what order... etc. Supporting some form of history might help to solve questions when players as about the validity of the current ladder order.

**Comment by seldomskye** [comment]
Yeah, should be possible, but I'm not sure what exactly the best way to render that is.
I think a list of matches played from last week is definitely worth adding, and maybe a way to put in a players name and see all matches they were involved in?

**Comment by seldomskye** [comment]
The code for this and displaying the last 20 matches will be ready for next week

daeadded9066600f8f6743b18f1952a0beb57bc8
d5583052ae567026985778569b1ade70f8488ef8

**Comment by seldomskye** [comment]
7ea0cda3b3e6499143a97bf56e3d2e226309da97
